src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import Custom404View

handler404 = Custom404View.as_view()

urlpatterns = [
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("core.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from core.views import (
    IndexView,
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    ActivateUserView,
    UpdateUserProfileView,
    UserProfileView,
)

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path(
        "activate/<str:uuid64>/<str:token>",
        ActivateUserView.as_view(),
        name="activate_user",
    ),
    path(
        "user_profile/<int:pk>",
        UserProfileView.as_view(),
        name="user_profile",
    ),
    path(
        "update_user_profile/<int:pk>",
        UpdateUserProfileView.as_view(),
        name="update_user_profile",
    ),
]

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupListView,
    GroupDetailView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>", DeleteGroupView.as_view(), name="delete_group"),
    path("group-details/<int:pk>", GroupDetailView.as_view(), name="get_group_details"),
]

src/students/urls.py
from django.urls import path

from students.views import (
    CreateStudentView,
    UpdateStudentView,
    DeleteStudentView,
    StudentListView,
)

app_name = "students"

urlpatterns = [
    path("", StudentListView.as_view(), name="get_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>", DeleteStudentView.as_view(), name="delete_student"),
]

src/students/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from faker import Faker

from core.models import PersonModel
from core.utils.validators import validate_file_size
from groups.models import Group
from students.utils.validators import (
    first_name_validator,
    grade_validator,
    extension_validator,
)


class Student(PersonModel):
    first_name = models.CharField(
        max_length=120,
        validators=[MinLengthValidator(2), first_name_validator],
        verbose_name="First name",
    )
    grade = models.PositiveSmallIntegerField(default=0, validators=[grade_validator], verbose_name="Grade")
    photo = models.ImageField(
        upload_to="images/students/",
        default="images/default.jpg",
        validators=[validate_file_size],
        verbose_name="Photo",
    )
    resume = models.FileField(
        upload_to="students_resume/",
        blank=True,
        null=True,
        validators=[extension_validator, validate_file_size],
        verbose_name="Resume",
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        null=True,
        related_name="student",
        verbose_name="Group",
    )

    @classmethod
    def generate_students(cls, count: int) -> None:
        faker = Faker()
        group_ids = Group.objects.values_list("id", flat=True)
        for i in range(count):
            group_id = faker.random.choice(group_ids)
            student = Student(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                grade=faker.random_number(digits=2),
                birth_date=faker.date_of_birth(minimum_age=16, maximum_age=60),
                group_id=group_id,
            )
            student.save()

    def __str__(self):
        return f"{self.first_name}, {self.last_name}, {self.email}, {self.grade}, {self.birth_date}, ({self.uuid})"

src/students/forms.py
from core.forms import PersonForm
from students.models import Student


class StudentForm(PersonForm):
    class Meta:
        model = Student
        fields = [
            "first_name",
            "last_name",
            "email",
            "grade",
            "birth_date",
            "photo",
            "resume",
            "group",
        ]

src/students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from students.forms import StudentForm
from students.models import Student


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "students/list.html"
    context_object_name = "students"
    queryset = Student.objects.select_related("group").all()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_value = self.request.GET.get("search")
        if search_value:
            or_filter = Q()
            search_fields = [
                "first_name",
                "last_name",
                "email",
                "grade",
                "birth_date",
                "group__name",
            ]
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": search_value})
            queryset = queryset.filter(or_filter)
        return queryset


class CreateStudentView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm
    template_name = "students/create.html"
    success_url = reverse_lazy("students:get_students")


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    template_name = "students/update.html"
    pk_url_kwarg = "uuid"
    queryset = Student.objects.all()
    success_url = reverse_lazy("students:get_students")


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Student
    template_name = "students/delete.html"
    pk_url_kwarg = "uuid"
    success_url = reverse_lazy("students:get_students")

src/templates/students/create.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Create">
    </form>
{% endblock content %}

src/templates/students/delete.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <table class="table table-hover table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">Photo</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Grade</th>
                <th scope="col">Birth Date</th>
                <th scope="col">Age</th>
                <th scope="col">Resume</th>
                <th scope="col">Group Name</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <img src="{{ student.photo.url }}" alt="Student Photo" style="max-width: 100px;">
                </td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.grade }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}
                <td>
                    {% if student.resume %}
                        <a href="{{ student.resume.url }}">{{ student.resume }}</a>
                    {% else %}
                        Empty
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'groups:get_group_details' student.group.pk %}">{{ student.group.name }}</a>
                </td>
            </tr>
            </tbody>
        </table>
        <input type="submit" class="btn btn-primary" value="Delete">
    </form>
{% endblock content %}

src/templates/students/list.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mb-3">
        <div class="col-auto">
            <form class="d-flex" method="GET" action="{% url 'students:get_students' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
        </div>
    </div>

    <table class="table table-hover table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Photo</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Grade</th>
            <th scope="col">Birth Date</th>
            <th scope="col">Age</th>
            <th scope="col">Resume</th>
            <th scope="col">Group Name</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>

        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>
                    <img src="{{ student.photo.url }}" alt="Student Photo" style="max-width: 100px;">
                </td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.grade }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}
                <td>
                    {% if student.resume %}
                        <a href="{{ student.resume.url }}">{{ student.resume }}</a>
                    {% else %}
                        Empty
                    {% endif %}
                </td>
                <td>
                    {% if student.group %}
                        <a href="{% url 'groups:get_group_details' student.group.pk %}">{{ student.group.name }}</a>
                    {% else %}
                        No Group
                    {% endif %}
                </td>
                <td>
                    <a type="button" class="btn btn-warning"
                       href={% url 'students:update_student' student.uuid %}>Edit
                    </a>
                </td>
                <td>
                    <a type="button" class="btn btn-danger"
                       href={% url 'students:delete_student' student.uuid %}>Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/students/update.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Update">
    </form>
{% endblock content %}