src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import Custom404View

handler404 = Custom404View.as_view()

urlpatterns = [
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("core.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from core.views import (
    IndexView,
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    ActivateUserView,
    UpdateUserProfileView,
    UserProfileView,
)

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path(
        "activate/<str:uuid64>/<str:token>",
        ActivateUserView.as_view(),
        name="activate_user",
    ),
    path(
        "user_profile/<int:pk>",
        UserProfileView.as_view(),
        name="user_profile",
    ),
    path(
        "update_user_profile/<int:pk>",
        UpdateUserProfileView.as_view(),
        name="update_user_profile",
    ),
]

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupListView,
    GroupDetailView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>", DeleteGroupView.as_view(), name="delete_group"),
    path("group-details/<int:pk>", GroupDetailView.as_view(), name="get_group_details"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import (
    TeacherDetailView,
    TeacherListView,
    CreateTeacherView,
    UpdateTeacherView,
    DeleteTeacherView,
)

app_name = "teachers"

urlpatterns = [
    path("", TeacherListView.as_view(), name="get_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:uuid>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:uuid>", DeleteTeacherView.as_view(), name="delete_teacher"),
    path(
        "teacher_detail/<uuid:uuid>",
        TeacherDetailView.as_view(),
        name="get_teacher_details",
    ),
]

src/teachers/models.py
from django.db import models
from faker import Faker

from core.models import PersonModel
from core.utils.validators import validate_file_size
from groups.models import Group
from teachers.utils.validators import (
    rating_validator,
    phone_number_validator,
)


class Teacher(PersonModel):
    degree = models.CharField(max_length=200, blank=True, null=True)
    rating = models.DecimalField(max_digits=3, decimal_places=1, default=0.0, validators=[rating_validator])
    phone_number = models.CharField(max_length=15, blank=True, null=True, validators=[phone_number_validator])
    photo = models.ImageField(
        upload_to="images/teachers/", default="images/default.jpg", validators=[validate_file_size]
    )
    group = models.ManyToManyField(Group, related_name="teacher")

    @classmethod
    def generate_teachers(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            teacher = Teacher(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(),
                degree=faker.word(),
                rating=faker.pyfloat(left_digits=1, right_digits=1, positive=True),
                phone_number=faker.phone_number(),
            )
            teacher.save()

    def __str__(self):
        return (
            f"{self.first_name}, {self.last_name}, {self.email}, {self.rating}, {self.birth_date}, "
            f"{self.phone_number}, ({self.uuid})"
        )

src/teachers/forms.py
from core.forms import PersonForm
from teachers.models import Teacher


class TeacherForm(PersonForm):
    class Meta:
        model = Teacher
        fields = [
            "first_name",
            "last_name",
            "email",
            "birth_date",
            "degree",
            "rating",
            "phone_number",
            "photo",
            "group",
        ]

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)


from teachers.forms import TeacherForm
from teachers.models import Teacher


class TeacherListView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = "teachers/list.html"
    context_object_name = "teachers"
    queryset = Teacher.objects.prefetch_related("group").all()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_value = self.request.GET.get("search")
        if search_value:
            or_filter = Q()
            search_fields = [
                "first_name",
                "last_name",
                "email",
                "degree",
                "rating",
                "phone_number",
                "birth_date",
                "group__name",
            ]
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": search_value})
            queryset = queryset.filter(or_filter)
        return queryset


class TeacherDetailView(LoginRequiredMixin, DetailView):
    model = Teacher
    template_name = "teachers/teacher_details.html"
    pk_url_kwarg = "uuid"
    context_object_name = "teacher"


class CreateTeacherView(LoginRequiredMixin, CreateView):
    model = Teacher
    template_name = "teachers/create.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherForm
    template_name = "teachers/update.html"
    pk_url_kwarg = "uuid"
    queryset = Teacher.objects.all()
    success_url = reverse_lazy("teachers:get_teachers")


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    template_name = "teachers/delete.html"
    pk_url_kwarg = "uuid"
    success_url = reverse_lazy("teachers:get_teachers")

src/templates/teachers/create.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Create">
    </form>
{% endblock content %}

src/templates/teachers/delete.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table class="table table-hover table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">Photo</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Birth Date</th>
                <th>Age</th>
                <th>Degree</th>
                <th>Rating</th>
                <th>Phone Number</th>
                <th>Group Name</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <img src="{{ teacher.photo.url }}" alt="Teacher Photo" style="max-width: 100px;">
                </td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                {% if teacher.birth_date %}
                    <td>{{ teacher.birth_date }}</td>
                    <td>{{ teacher.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}
                <td>{{ teacher.degree }}</td>
                <td>{{ teacher.rating }}</td>
                <td>{{ teacher.phone_number }}</td>
                <td>
                    {% for group in teacher.group.all %}
                        <a href="{% url 'groups:get_group_details' group.pk %}">{{ group.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                    {% empty %}
                        Empty
                    {% endfor %}
                </td>
            </tr>
            </tbody>
        </table>
        <input type="submit" class="btn btn-primary" value="Delete">
    </form>
{% endblock content %}

src/templates/teachers/list.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mb-3">
        <div class="col-auto">
            <form class="d-flex" method="GET" action="{% url 'teachers:get_teachers' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
        </div>
    </div>

    <table class="table table-hover table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Photo</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Birth Date</th>
            <th>Age</th>
            <th>Degree</th>
            <th>Rating</th>
            <th>Phone Number</th>
            <th>Group Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <td>
                    <img src="{{ teacher.photo.url }}" alt="Teacher Photo" style="max-width: 100px;">
                </td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                {% if teacher.birth_date %}
                    <td>{{ teacher.birth_date }}</td>
                    <td>{{ teacher.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}
                <td>{{ teacher.degree }}</td>
                <td>{{ teacher.rating }}</td>
                <td>{{ teacher.phone_number }}</td>
                <td>
                    {% for group in teacher.group.all %}
                        <a href="{% url 'groups:get_group_details' group.pk %}">{{ group.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                    {% empty %}
                        Empty
                    {% endfor %}
                </td>
                <td>
                    <a type="button" class="btn btn-warning"
                       href={% url 'teachers:update_teacher' teacher.uuid %}>Edit
                    </a>
                </td>
                <td>
                    <a type="button" class="btn btn-danger"
                       href={% url 'teachers:delete_teacher' teacher.uuid %}>Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/teachers/teacher_details.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <table class="table table-hover table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Photo</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Birth Date</th>
            <th>Age</th>
            <th>Degree</th>
            <th>Rating</th>
            <th>Phone Number</th>
            <th>Group Name</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <img src="{{ teacher.photo.url }}" alt="Teacher Photo" style="max-width: 100px;">
            </td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.email }}</td>
            {% if teacher.birth_date %}
                <td>{{ teacher.birth_date }}</td>
                <td>{{ teacher.age }}</td>
            {% else %}
                <td>Unknown</td>
                <td>Unknown</td>
            {% endif %}
            <td>{{ teacher.degree }}</td>
            <td>{{ teacher.rating }}</td>
            <td>{{ teacher.phone_number }}</td>
            <td>
                {% for group in teacher.group.all %}
                    <a href="{% url 'groups:get_group_details' group.pk %}">{{ group.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% empty %}
                    Empty
                {% endfor %}
            </td>
        </tr>
        </tbody>
    </table>
{% endblock content %}

src/templates/teachers/update.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Update">
    </form>
{% endblock content %}