src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import Custom404View

handler404 = Custom404View.as_view()

urlpatterns = [
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("core.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from core.views import (
    IndexView,
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    ActivateUserView,
    UpdateUserProfileView,
    UserProfileView,
)

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path(
        "activate/<str:uuid64>/<str:token>",
        ActivateUserView.as_view(),
        name="activate_user",
    ),
    path(
        "user_profile/<int:pk>",
        UserProfileView.as_view(),
        name="user_profile",
    ),
    path(
        "update_user_profile/<int:pk>",
        UpdateUserProfileView.as_view(),
        name="update_user_profile",
    ),
]

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupListView,
    GroupDetailView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>", DeleteGroupView.as_view(), name="delete_group"),
    path("group-details/<int:pk>", GroupDetailView.as_view(), name="get_group_details"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import (
    TeacherDetailView,
    TeacherListView,
    CreateTeacherView,
    UpdateTeacherView,
    DeleteTeacherView,
)

app_name = "teachers"

urlpatterns = [
    path("", TeacherListView.as_view(), name="get_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:uuid>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:uuid>", DeleteTeacherView.as_view(), name="delete_teacher"),
    path(
        "teacher_detail/<uuid:uuid>",
        TeacherDetailView.as_view(),
        name="get_teacher_details",
    ),
]

src/groups/models.py
from datetime import datetime, timedelta

from django.db import models
from faker import Faker

from groups.utils.validator import (
    group_rating_validator,
    number_of_lessons_validator,
    expected_end_date_validator,
)


class Group(models.Model):
    name = models.CharField(max_length=255)
    creation_date = models.DateField(auto_now_add=True)
    rating = models.DecimalField(max_digits=3, decimal_places=1, default=0.0, validators=[group_rating_validator])
    description = models.TextField(blank=True, null=True)
    number_of_lessons = models.IntegerField(default=0, validators=[number_of_lessons_validator])
    expected_end_date = models.DateField(null=True, blank=True, validators=[expected_end_date_validator])

    @classmethod
    def generate_groups(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            today = datetime.now().date()
            end_date_max = today + timedelta(days=365)
            group = Group(
                name=faker.word(),
                rating=faker.pyfloat(left_digits=1, right_digits=1, positive=True),
                description=faker.paragraph(nb_sentences=3),
                number_of_lessons=faker.random_number(digits=2),
                expected_end_date=faker.date_between(start_date=today, end_date=end_date_max),
            )
            group.save()

    def __str__(self):
        return f"{self.name}, {self.id}"

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from groups.form import GroupForm
from groups.models import Group


class GroupListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = "groups/list.html"
    context_object_name = "groups"
    queryset = Group.objects.prefetch_related("teacher").annotate(student_count=Count("student"))

    def get_queryset(self):
        queryset = super().get_queryset()
        search_value = self.request.GET.get("search")
        if search_value:
            or_filter = Q()
            search_field = [
                "name",
                "rating",
                "description",
                "number_of_lessons",
                "expected_end_date",
                "teacher__first_name",
                "teacher__last_name",
            ]
            for field in search_field:
                or_filter |= Q(**{f"{field}__icontains": search_value})
            queryset = queryset.filter(or_filter)
        return queryset


class GroupDetailView(LoginRequiredMixin, DetailView):
    model = Group
    template_name = "groups/group_details.html"
    queryset = Group.objects.all()
    context_object_name = "group"


class CreateGroupView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = "groups/create.html"
    success_url = reverse_lazy("groups:get_groups")


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupForm
    queryset = Group.objects.all()
    template_name = "groups/update.html"
    success_url = reverse_lazy("groups:get_groups")


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = "groups/delete.html"
    success_url = reverse_lazy("groups:get_groups")

src/templates/groups/create.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Create">
    </form>
{% endblock content %}

src/templates/groups/delete.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <table class="table table-hover table-dark table-striped">
            <thead>
            <tr>
                <th>Group Name</th>
                <th>Group Rating</th>
                <th>Group Description</th>
                <th>Number of Lessons</th>
                <th>Expected End Date</th>
                <th>Number of students</th>
                <th>Teacher First and Second Name</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ group.name }}</td>
                <td>{{ group.rating }}</td>
                <td>{{ group.description }}</td>
                <td>{{ group.number_of_lessons }}</td>
                <td>{{ group.expected_end_date }}</td>
                <td>{{ group.student.count }}</td>
                <td>
                    {% for teacher in group.teacher.all %}
                        <a href="{% url 'teachers:get_teacher_details' teacher.uuid %}">
                            {{ teacher.first_name }} {{ teacher.last_name }}
                            {% if not forloop.last %}, {% endif %}
                        </a>
                    {% empty %}
                        Empty
                    {% endfor %}
                </td>
            </tr>
            </tbody>
        </table>
        <input type="submit" class="btn btn-primary" value="Delete">
    </form>
{% endblock content %}

src/templates/groups/group_details.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="get">
        <table class="table table-hover table-dark table-striped">
            <thead>
            <tr>
                <th>Group Name</th>
                <th>Group Rating</th>
                <th>Group Description</th>
                <th>Number of Lessons</th>
                <th>Expected End Date</th>
                <th>Number of students</th>
                <th>Teacher First and Second Name</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ group.name }}</td>
                <td>{{ group.rating }}</td>
                <td>{{ group.description }}</td>
                <td>{{ group.number_of_lessons }}</td>
                <td>{{ group.expected_end_date }}</td>
                <td>{{ group.student.count }}</td>
                <td>
                    {% for teacher in group.teacher.all %}
                        <a href="{% url 'teachers:get_teacher_details' teacher.uuid %}">
                            {{ teacher.first_name }} {{ teacher.last_name }}
                            {% if not forloop.last %}, {% endif %}
                        </a>
                    {% empty %}
                        Empty
                    {% endfor %}
                </td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock content %}

src/templates/groups/list.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mb-3">
        <div class="col-auto">
            <form class="d-flex" method="GET" action="{% url 'groups:get_groups' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
        </div>
    </div>

    <table class="table table-hover table-dark table-striped">
        <thead>
        <tr>
            <th>Group Name</th>
            <th>Group Rating</th>
            <th>Group Description</th>
            <th>Number of Lessons</th>
            <th>Expected End Date</th>
            <th>Number of students</th>
            <th>Teacher First and Second Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr>
                <td>{{ group.name }}</td>
                <td>{{ group.rating }}</td>
                <td>{{ group.description }}</td>
                <td>{{ group.number_of_lessons }}</td>
                <td>{{ group.expected_end_date }}</td>
                <td>{{ group.student_count }}</td>
                <td>
                    {% for teacher in group.teacher.all %}
                        <a href="{% url 'teachers:get_teacher_details' teacher.uuid %}">
                            {{ teacher.first_name }} {{ teacher.last_name }}
                            {% if not forloop.last %}, {% endif %}
                        </a>
                    {% empty %}
                        Empty
                    {% endfor %}
                </td>

                <td>
                    <a type="button" class="btn btn-warning"
                       href={% url 'groups:update_group' group.pk %}>Edit
                    </a>
                </td>
                <td>
                    <a type="button" class="btn btn-danger"
                       href={% url 'groups:delete_group' group.pk %}>Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/groups/update.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="post" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Update">
    </form>
{% endblock content %}